executors:
  - name: demo-hpc
    connector:
      ssh:
        host: demo-hpc
        base_dir: ./tmp/taskspec-demo
    runner:
      slurm: {}

server_url: http://127.0.0.1:8011
public_url: http://10.26.14.77:9009
